### ISSUE TITLE
no way of adding client_secret

### ISSUE THREAD

**Issue by barranger** [GSingh01/ad-b2c-react-native#10]
I'm running into the following error message and don't have a way of specifying the `client_secret`

```
AADB2C90079: Clients must send a client_secret when redeeming a confidential grant.
```

Any help would be greatly appreciated

**Comment by GSingh01** [comment]
Thanks for commenting. Client secret suppose to be a secret and should never be added on client side application. They are usually for backend to auth service communication.

Since the LoginView doesnot require it and none of the documented methods requires that, What are you tryng to do exactly?

**Comment by barranger** [comment]
Thanks for the quick reply!

I'm trying to log in and get the Auth Token.  It brings up the login page, and allows for the first login, but then will fail with the above message.  When I re-launch the app it goes right to the Error.

Here's my LoginView Element (with info removed of course):

```
 return (
      <LoginView
        appId="[my app/client id]"
        redirectURI="http://localhost:3000"
        tenant="[my-token]"
        loginPolicy="B2C_1_SignIn"
        onSuccess={this.onLogin}
        onFail={this.onFail}
        secureStore={SecureStore}
        renderLoading={this.spinner}
      />
```

I was able to use a [different lib](https://github.com/sonyarouje/react-native-ad-b2c) to get the token, but it's certainly not as well kept as this lib.

**Comment by GSingh01** [comment]
Given that you recently got the token and is not expired it should not call the auth service for new token unless user logged out. Please verify the way  library is used or create a sample app to reproduce so that I can take a look.

Also please carefully look at docs again for correct implementation, since it should not require client secret in first place in any of the calls made.

**Comment by GSingh01** [comment]
Also please make sure your App ID is registered as native app not web app in Azure B2C portal

**Comment by barranger** [comment]
Thank you very much it was your second comment, I needed to create a new App Registration that was specific for the Mobile Application.

Marking as closed
