### ISSUE TITLE
Expo signin to our tenant works once

### ISSUE THREAD

**Issue by stevef51** [GSingh01/ad-b2c-react-native#13]
First up - RN is pretty new to me, but loving it
Second - I am finding help on Azure B2C with RN is extremely limited, this is by far the most helpful utility out there
I have taken your sample Login component and plugged in my tenant details ..

      <LoginView
        appId="7f0ce0c1-32a5-418a-b3e5-a240b6c9305c"
        redirectURI="https://jwt.ms"
        tenant="smartarmour"
        loginPolicy="B2C_1_signupsignin1"
        passwordResetPolicy="B2C_1_PasswordReset"
        profileEditPolicy="B2C_1_ProfileEdit"
        onSuccess={this.onLogin}
        onFail={this.onFail}
        secureStore={this.MySecureStore}
        renderLoading={this.spinner}
        userAgent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36"
      />

Our current B2C tenant is setup to allow Google provider (we will add others later), when I fire up the App on simulator or real iOS device the login page presents properly, if I choose "Google" it originally errored with "invalid_useragent" which is why I had to force the userAgent in the Webview, this now works.

So I login with my Google account and it proceeds to a display a fully white screen.  

Wierdly, if I restart the App (or shake and refresh Expo) it goes back to the Login screen and if I hit "Google" then it freezes and does nothing, the Google button is shown to be pressed but does not navigate to Google login page

**Comment by GSingh01** [comment]
@stevef51 please update to latest version 1.1.2

**Comment by stevef51** [comment]
Thanks - as it turned out, I decided to port your JS code to TypeScript, a) to give me better intellisense and b) it forced me into actually understanding what your library was doing.
As it turned out the changes in your 1.1.2 are 99% same as the fixes I came up with which is good - you should also note that the WebView event "onNavigationStateChangeAsync" gets called twice for each navigation, one when it starts to load and one when it finishes loading, I added an extra filter to only use the Start event ..

    const onNavigationStateChangeAsync = async (navState: WebViewNavigation) => {
        // Only interested when we start loading
        if (!navState.loading) {
            return;
        }
        ...

additionally, the "onShouldStartLoadWithRequest" event I dont think is needed, I have taken it out completely and the flow still results in a generated token.

I also added the "incognito" prop which does address the issue of Google IDP remembering my previously selected user, it does however also mean it forgets everything, so you have to fully log back in - there doesn't seem to be a neat way of making the flow follow the same Desktop experience where Google IDP prompts me for a list of known accounts.  

Thanks for your hard work on this library :)

**Comment by GSingh01** [comment]
@stevef51  thats awesome,please feel free to create a PR with the change. 
Also1.1.2 has incognito mode and user agent added by default and are overridable.

**Comment by stevef51** [comment]
@GSingh01 Ok, I have spent this whole morning attempting to prepare for a PR, the big part of the change is the porting to TypeScript - although my tiny App runs fine with the port the Jest tests fail miserably (all of them I think) - not quite up to speed on npm, typescript, expo, jest etc in order to address this currently - the only change I think you would be interested in for the JS source is the "onNavigationStateChangeAsync" change I mentioned in previous post

**Comment by GSingh01** [comment]
@stevef51 thanks, i will make that edit in future. But for now one should be able to use library as is. If you agree please close the issue
