### ISSUE TITLE
Create Typescript typings

### ISSUE THREAD

**Issue by nmehlei** [GSingh01/ad-b2c-react-native#14]
It would definitely make it easier to use this library if there were Typescript typings available. It would have probably avoided ticket #3 . Unfortunately, currently, I don't have the extra spare time, otherwise, I would've volunteered to create them myself.

**Comment by GSingh01** [comment]
Hello nmehlei,  agree but were you able to get past the issue using suggestions in #3

**Comment by nmehlei** [comment]
@GSingh01 Still in progress, I used the following lines for now:
const AdB2cReactNative = require('ad-b2c-react-native');
var LoginView = AdB2cReactNative.LoginView;

I'm currently stuck at a different point: Is this project tightly coupled to expo-secure-store? As I did not include expo during project creation, this is currently blocking my auth integration. Can a different store be used instead of the expo implementation? If no, shouldn't expo be added as an explicit dependency as expo integration is not mandatory in each project?

**Comment by GSingh01** [comment]
@nmehlei no its not tightly coupled to expo-secure-store but from readme file below are the comments:

      //for secureStore, you can pass expo's secure store or create your own wrapper, 
      //which implements deleteItemAsync(key), getItemAsync(key), setItemAsync(key, data)

So in this case you have to create your own store for deleteItemAsync(key), getItemAsync(key), setItemAsync(key, data) to **securely** store the token info.
other wise just install it(https://www.npmjs.com/package/expo-secure-store)

Hopefully that helps

**Comment by nmehlei** [comment]
@GSingh01 Thank you for your quick responses! And I must have completely missed that comment. I built the following wrapper around react-native-community/async-storage.

```
class SecureStoreWrapper {
    public deleteItemAsync(key: string): Promise<any> {
        return AsyncStorage.removeItem(key);  
    }

    public getItemAsync(key: string): Promise<any> {
        return AsyncStorage.getItem(key);   
    }

    public setItemAsync(key: string, data: any): Promise<any> {
        return AsyncStorage.setItem(key, data);  
    }
}
```

During quick tests, this class seems to work. Unfortunately, the overall ad-b2c integration currently only shows a quick loading spinner and then a white screen without any errors or warnings. Probably I'm still missing something, but might I suggest optimizing the resiliency and/or error/warning output? It's hard to find the problem with no output whatsoever, but maybe this could be made easier for the next person with a few helpful checks in the code?

**Comment by nmehlei** [comment]
@GSingh01 That's true, but at least in my case that does not seem to be enough. The handlers for onSuccess, onFail as well as renderLoading are set but only renderLoading is invoked.

Basically the execution that I can observe from logging is as follows:
1) renderLoading
2) my secure store wrapper for key tokenType
3) my secure store wrapper for key accessToken
4) my secure store wrapper for key refreshToken
5) my secure store wrapper for key idToken
6) my secure store wrapper for key expiresOn
7) renderLoading

And just after typing this and looking into the source code of ADService.js a bit more I found the problem. I set the tenant to myTenantName.onmicrosoft.com instead of the expected myTenantName. Some other libraries expect this value with this onmicrosoft.com suffix, but I should've double-checked it in the source code. Maybe a quick check with a logged warning might be good here.

(I didn't remove the first half of this comment because it might help someone else who might see the same pattern in his or her code)

Thanks @GSingh01, awesome library!

**Comment by GSingh01** [comment]
@nmehlei library expects that if login url is wrong then browser page will show page not found error etc. Based on above looks like it didnot happen to you and came back with a blank page.
Can you try that incorrect url in indepent browser and check if you get simular blank screen.

**Comment by nmehlei** [comment]
@GSingh01 I understand. I just tested the generated URL and since it results in something like myTenantName.onmicrosoft.com.b2clogin.com, which fails with an SSL certificate error and an understandable 404 response. I assume that the SSL certificate error might be the reason why it only shows the blank page.

**Comment by GSingh01** [comment]
@nmehlei new version is released with typescript
