### ISSUE TITLE
Where is the client_secret handled?

### ISSUE THREAD

**Issue by inexplicable01** [GSingh01/ad-b2c-react-native#16]
Hi, Looking to implement your package in my react native app for B2C sign in.

How does this package handle the client_secret?  It doesn't appear to be in here or am I missing something?

Thanks. 

I will be more than glad to contribute also if it is indeed missing.

**Comment by GSingh01** [comment]
Hello @inexplicable01  thanks for the question. Client secret is only required when one need to authenticate on backend api or in short api -> auth api. On client apps one should never use client secret as it is not secure to expose it on client app.Further it will defy the whole purpose of username and password.

Please make sure you create you app as Native client in Azure AD B2C portal and then just provide the info required in doc to the login component and you should be good. 

Feel free to ask.

**Comment by inexplicable01** [comment]
Hi Thank you so much for your reply.   Definitely am learning a lot here.

So all the Webapi needs for authentication is the token from B2C.   Thanks again.

**Comment by GSingh01** [comment]
@inexplicable01  yes, your web api should consume and validate the access_token(not id token) that you get in your app using this package(or another). 
my pleasure man. Thanks
