### ISSUE TITLE
Error on login: Array Methods must be provided an Array

### ISSUE THREAD

**Issue by michaelfsarkis** [GSingh01/ad-b2c-react-native#17]
Hi,

 I am receiving this error after successful logging in.
 I believe the error is coming from the method: _setTokenDataAsync
The promise.all inputs are not within an array in the package. I think the inputs in the promise need to be containes in an array as below
```
await Promise.all([
      this.secureStore.setItemAsync(this.TokenTypeKey, res.token_type),
      this.secureStore.setItemAsync(this.AccessTokenKey, res.access_token),
      this.secureStore.setItemAsync(this.RefreshTokenKey, res.refresh_token),
      this.secureStore.setItemAsync(this.IdTokenKey, res.id_token),
      this.secureStore.setItemAsync(
        this.ExpiresOnKey,
        res.expires_on.toString()
      )
      ]);```

**Comment by GSingh01** [comment]
@michaelfsarkis Thanks for reporting issue.
Are you using a custom scope if yes make sure you have openid offline_access inaddition to custom scopes.
For more info check out the comment related in readme.txt

Let me know if this resolves your issue.

Thanks

**Comment by GSingh01** [comment]
@michaelfsarkis  to add your suggestion above makes sense so i have new change pushed please check the release 1.1.4. hopefully that resolves your issue
Thanks again for letting me know. Appreciated 👍

**Comment by michaelfsarkis** [comment]
Thanks mate.
Working well now :)
