### ISSUE TITLE
Error in LoginView

### ISSUE THREAD

**Issue by yumoraby** [GSingh01/ad-b2c-react-native#2]
Following the code for LoginView has several errors:

- returns an error for {spinner} I believe it should be {this.spinner}
- CView & Spinner are they valid components? If so where are they imported from?
- Navigate to this component yields not action in React Native with Expo SDK 35

```javascript
import React from 'react';
import { Alert } from 'react-native';
import { LoginView } from 'ad-b2c-react-native';
import * as SecureStore from 'expo-secure-store';

export default class Login extends React.PureComponent {
  static navigationOptions = { header: null };

  constructor(props) {
    super(props);
    this.onLogin = this.onLogin.bind(this);
    this.onFail = this.onFail.bind(this);
    this.spinner = this.spinner.bind(this);
  }

  onLogin() {
    const { navigation } = this.props;
    navigation.navigate('App');
  }

  onFail(reason) {
    Alert.alert(reason);
  }

  spinner() {
      return (
        <CView> 
            <Spinner />
        </CView>
    );  
  }

  render() {
      //apart from these props you can use any webview props
      //for secureStore, you can pass expo's secure store or create your own wrapper, 
      //which implements deleteItemAsync(key), getItemAsync(key), setItemAsync(key, data)
    
    return (
      <LoginView
        appId="myAppId"
        redirectURI="myRedirectURI"
        tenant="myTenant"
        loginPolicy="B2C_1_SignUpSignIn"
        passwordResetPolicy="B2C_1_PasswordReset"
        profileEditPolicy="B2C_1_ProfileEdit"
        onSuccess={this.onLogin}
        onFail={this.onFail}
        secureStore={MySecureStore}
        renderLoading={spinner}     
      />
    );
  }
}
```

**Comment by GSingh01** [comment]
Yes it should be this.spinner.

Further, the sample code serves the purpose of just illustrating the properties and copy paste will not work.

Spinner and CView are custom components.In your case, Spinner can be replaced with any loading symbol you wish to use and CView is just a wrapper around React Native's View.


I am personally using this library and haven't encountered the error you mentioned. Make sure the url and other properties are correct.

If after applying above changes still doesnot resolve, please provide the complete stack trace of the error.

Also the readme is updated to reflect your concerns. Thanks again for the feedback.

**Comment by yumoraby** [comment]
Thanks for the response:)

Will update and try again. Are you using Expo?

**Comment by GSingh01** [comment]
yes i use expo. i made few more updates to docs related to peer dependencies requirements. please check again.

**Comment by autumnblue** [comment]
how can I use this expo-secure-store package in non-expo run app?

**Comment by GSingh01** [comment]
Please refer to https://www.npmjs.com/package/expo-secure-store or else you can roll your own implementation based on info provided in readme.
Hope this helps
