### ISSUE TITLE
Error on Login :  res.expires_on

### ISSUE THREAD

**Issue by chandana-2019** [GSingh01/ad-b2c-react-native#24]
Hi @GSingh01 , 

I am receiving this error after logging in

![B2c_Image](https://user-images.githubusercontent.com/53889546/98464562-c750f400-21e9-11eb-9029-2650d3d486a7.png)

 **undefined is not an object(evaluating 'res.expires_on......')**

Below is the code : 

onLogin = async () => {
        try {
          const credentials = await SecureStore.getItemAsync('key');
          console.log('value of credentials: ', credentials);
          if (credentials) {
            const myJson = JSON.parse(credentials);
            const { navigation } = this.props;
            navigation.navigate('App');
          }
        } catch (e) {
          console.log(e);
        }
      };

 <LoginView
          appId="*****myAppId*****"
          redirectURI="*****myredirectURI*******" 
          tenant="***Myteneant******"
          loginPolicy="B2C_1_Sign_In_Sign_up"
          passwordResetPolicy="B2C_1_Password_Reset"
          //profileEditPolicy="B2C_1_ProfileEdit"
          onSuccess={this.onLogin}
          onFail={this.onFail}
          secureStore={SecureStore}
          renderLoading={this.spinner}
          scope="openid offline_access" 
        />

Is this error due to SecureStore configuration ? Kindly guide how can I use SecureStore with ad-b2c-react-native as there isn't much helpul docs for the same .

**Comment by GSingh01** [comment]
@chandana-2019 Docs mentions this about secure store:
```
//for *secureStore*, you can pass expo's secure store or create your own wrapper,
//which implements deleteItemAsync(key), getItemAsync(key), setItemAsync(key, data)
```
So based on above either install expo-secure-store or write your own module that have mentioned methods.
Further check https://github.com/GSingh01/ad-b2c-react-native/issues/2 for discussion on similar topic.

Thanks

**Comment by ocasiom** [comment]
I also hit this issue and found that B2C is no longer using "expiresOn" as the key for the token expiration. In my case I am getting "id_token_expires_in" and "refresh_token_expires_in" which causes the "undefined is not an object (evaluating 'res.expires_on.toString')"

**Comment by GSingh01** [comment]
@ocasiom based on documentation here https://docs.microsoft.com/en-us/azure/active-directory-b2c/access-tokens it seems it is using expires_on please verify
