### ISSUE TITLE
Error on Login but works after on reload only while using custom scope

### ISSUE THREAD

**Issue by albin-joseph-wiznet** [GSingh01/ad-b2c-react-native#25]
Error on Login but works after reload,  error occurs only while using custom scope.

**ERROR SAYS:-**
**"Invalid value provided to SecureStore. Values must be strings; consider JSON-encoding your values if they are serializable."**

-1st time execution"onFail={this.onFail}" (ON CUSTOM SCOPE)
-2nd time execution "onSuccess={this.onLogin}" (On RELOAD)

**EXPECTED:-**
-1st time execution "onSuccess={this.onLogin}" 
-2nd time execution "onSuccess={this.onLogin}"

**Comment by GSingh01** [comment]
@albin-joseph-wiznet make sure your scope is specified like `openid offline_access {your scope}` . This also mentioned in docs. Further read https://github.com/GSingh01/ad-b2c-react-native/issues/15 for more info.

Thanks
