### ISSUE TITLE
Buttons not Working for Edit userflow in IOS

### ISSUE THREAD

**Issue by radheaki** [GSingh01/ad-b2c-react-native#26]
Hi @GSingh01 

While We open the EditFlow and Click on Cancel button the Editflow not getting closed while freezes at the the EditView itself ,but working fine for android.
So I updated onShouldStartLoadWithRequest and added some code 
             if(....result.requestType === RequestType.Ignore .....){ .... this.webView.stopLoading()
//for  fix
       if(Platform.OS === 'ios'){
                   this._handleFlowResultAsync(result)
              }
return false;
.......}
This is working  fine for me .Is it a feasible solution??

Thankyou

**Comment by GSingh01** [comment]
@radheaki Please make sure you have latest version. 
But if the above solution works ya go ahead, I will also look in to it but that will take some time. Currently its little hard for me to devote extra time for the package but updates will coming in near future hopefully.

Thanks

**Comment by stefanab** [comment]
I'm experiencing the same issue with `passwordResetPolicy`. Had to had add `currentUri` to make it work.  

      `onShouldStartLoadWithRequest(navState) {
        const result = adService.getLoginFlowResult(navState.url);
        if (
          result.requestType === RequestType.Ignore ||
          result.requestType === RequestType.Code && !navState.loading ||
          result.requestType === RequestType.PasswordReset ||
          result.requestType === RequestType.Cancelled
        ) {
          if (Platform.OS === 'ios') {
              this._handleFlowResultAsyn(result, this.state.uri)
          }
          this.webView.stopLoading();
          return false;
        } 
        
       return true;
    }`

**Comment by GSingh01** [comment]
feel free to create PR for above and will be happy to review
