### ISSUE TITLE
Azure ADB2C in to the react native mobile application using expo cli - in login facing File or directory not found error

### ISSUE THREAD

**Issue by sdinesmvc** [GSingh01/ad-b2c-react-native#27]
I like to develop react native mobile application using expo cli. regarding that i integrate authenticate using azure adb2c.
in login 404 file or directory not found error Please find the configuration below and error screenshot
 <LoginView
                appId="334b4043-d862-4911-9bf3-f1caa5d12f8f"
              redirectURI=""
               tenant="myapp1"
               loginPolicy="B2C_1_signupsignin1"
                passwordResetPolicy="B2C_1_PasswordReset"
                profileEditPolicy="B2C_1_ProfileEdit"
                onSuccess={onLogin}
                onFail={onFail}
                secureStore={MySecureStore}
                renderLoading={() => { return (<View><Text>Loading</Text></View>) }}
                scope="openid offline_access" //optional, but see the notes above
            />

**Comment by sdinesmvc** [comment]
@GSingh01  How to expo react native project redirecturi in application and azure portal. Please help me.

**Comment by GSingh01** [comment]
@sdinesmvc sorry for late reply, i did not get time to pay attention to project past couple of months.
Please check the closed issues that are tagged as question, e.g: https://github.com/GSingh01/ad-b2c-react-native/issues/11

I hope it helps.

Thanks
