### ISSUE TITLE
Erorr when integrating the package into an ejected react-native app with typescript

### ISSUE THREAD

**Issue by arv-devperson** [GSingh01/ad-b2c-react-native#28]
After Installing the ad-b2c-react-native package with the dependencies mentioned in the documentation I am getting the following error:

ERROR    Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

I got inspiration from https://github.com/michaelburch repo who has implemented a sample project using ad-b2c-react-native. 
I have done a lot of search and it looks like it has something to do with **webview** but I am not sure how I can get around it.

I put a screenshot as well, just in case:

I'd really appreciate some help. Thanks!

![image](https://user-images.githubusercontent.com/75137028/104811877-d0b89700-57fe-11eb-88ba-f715459488be.png)

**Comment by kkhanhluu** [comment]
@arv-devperson did you get the solution?

**Comment by arv-devperson** [comment]
> 
> 
> @arv-devperson did you get the solution?

Yes I did. I ended up using an older version of web-view than stated in the documentation
