### ISSUE TITLE
Links "password reset" & "create account" not clickable on Android

### ISSUE THREAD

**Issue by joeybronner** [GSingh01/ad-b2c-react-native#29]
Hi, 

My form username / password was ok but all the others links were not clickable, especially: "password reset" & "create account". After removing `this.webView.stopLoading();` in the `onShouldStartLoadWithRequest` function, it worked as expected.

PS : this issue only happens on Android.

I thought it might help someone later ;)

Best,
Joey

**Comment by GSingh01** [comment]
Thanks for the info. Bit busy but will check what's happening there when get some time but ya if this workaround works, then in the mean time this is good.
Also welcome to create PR as well.
