### ISSUE TITLE
TS Error - Could not find a declaration file for module 'ad-b2c-react-native'

### ISSUE THREAD

**Issue by lemusthelroy** [GSingh01/ad-b2c-react-native#3]
When using below import...

`import { LoginView } from 'ad-b2c-react-native';`

I am getting the following error when using Typescript. 

"Could not find a declaration file for module 'ad-b2c-react-native'."... "implicitly has an 'any' type.
  Try `npm install @types/ad-b2c-react-native` if it exists or add a new declaration (.d.ts) file containing `declare module 'ad-b2c-react-native';"

Is there any easy fix to this?

**Comment by GSingh01** [comment]
Thanks for posting the issue.
The issue is due to no type info for the module.

A Google search revealed me the following and it should resolve your issue: https://stackoverflow.com/questions/41292559/could-not-find-a-declaration-file-for-module-module-name-path-to-module-nam

Thanks

**Comment by GSingh01** [comment]
@lemusthelroy, let me know if you were able to resolve using above. :)

Thanks
