### ISSUE TITLE
custom policies,  extraQueryParameters and help in Redirect URI

### ISSUE THREAD

**Issue by sultan-arshi** [GSingh01/ad-b2c-react-native#30]
i am trying to make some `custom policies`, is it possible to use it with this lib ?

**Comment by GSingh01** [comment]
Library allows you to specify your policy names as follows. Further check readme for more info
```
loginPolicy="B2C_1_SignUpSignIn"
passwordResetPolicy="B2C_1_PasswordReset"
profileEditPolicy="B2C_1_ProfileEdit"
```

**Comment by sultan-arshi** [comment]
thanks for the reply 
i have almost done but getting white screen even have provided all correct information 
one thing that may be incorrect is `scope`
basically i have made a scope in the `expose api` and have added it in the `api permission` and my application also have both permissions `openid` and `offline_access`
how could i use it in the scope ?
for now i am using 
`scope={"openid offline_access"}` but still have white screen in webView
are we required to provide scope separated by space ?

**Comment by sultan-arshi** [comment]
i append `extraQueryParameters` in the URL in the lib and it loaded my custom pages but now i am getting the error blow

`{"canGoBack": false, "canGoForward": false, "code": -1002, "description": "unsupported URL", "didFailProvisionalNavigation": true, "domain": "NSURLErrorDomain", "loading": false, "target": 15, "title": "Sign in", "url": "https://tenant.b2clogin.com/tenant.onmicrosoft.com/customPolicy/oauth2/v2.0/authorize?client_id=myApplicationId&response_type=code&redirect_uri=myRedirectURI&response_mode=query&scope=openid%20offline_access& extraQueryParameters KEY1= extraQueryParametersValue1& extraQueryParametersKEY2= extraQueryParametersVALUE2"}`

Is there any help to track it

**Comment by sultan-arshi** [comment]
i think the problem is in the redirect uri which in the case of mobile phones is may be have to put in different way
my redirect URI as it can be seen above in URL is `redirect_uri=msauth.bundleID://auth`
am i doing right ?

**Comment by sultan-arshi** [comment]
no help found from owner. anyhow, what i did 
just go to your azure portal => in your application => Authentication => `+ Add a platform` => `mobile and desktop application` => check (select) all the check mark available (in my case there were two) => configure => use this redirect URI (one of them will work)

**Comment by GSingh01** [comment]
in scope prop you are passing object whereas in readme it is space separated string. Carefully check

**Comment by sultan-arshi** [comment]
i have solved the problem 
the problem was redirect URI which i mentioned above

**Comment by charlestbell** [comment]
@sultan-arshi What exactly did you change?
