### ISSUE TITLE
Jest encountered an unexpected token

### ISSUE THREAD

**Issue by eswarant** [GSingh01/ad-b2c-react-native#32]
I am getting this error when run test file. Please help me on this.

Jest encountered an unexpected token.
This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

**Comment by GSingh01** [comment]
where are you having this error. Is it in your solution or it related to this library?
