### ISSUE TITLE
redirect url 

### ISSUE THREAD

**Issue by potatoengineer** [GSingh01/ad-b2c-react-native#36]
@GSingh01 Having trouble setting up proper redirect url for when a user completes a password reset. Deep linking to previous screen isn't working & localhost ends up with error.
```
Error loading page
Domain: NSURLErrorDomain
Error Code: -1004
Description: Could not connect to the server.
```

**Comment by GSingh01** [comment]
make sure the reset link doesnot match with actual app redirect url. Please check existing closed issue here: https://github.com/GSingh01/ad-b2c-react-native/issues/11
