### ISSUE TITLE
New Access Token not generating using the Refresh Token 

### ISSUE THREAD

**Issue by sambeet21** [GSingh01/ad-b2c-react-native#46]
Hi @GSingh01  I am doing the implementation of azureb2c in an app but the as per your Docs provided in readme the access token will seamlessly generated using the refresh token .. But that currently not happening ... Can you please guide me how to renew a access token before it expires using the refresh token ... [help wanted]

**Comment by sambeet21** [comment]
@GSingh01 please help

**Comment by GSingh01** [comment]
make sure you use correct scope, `openid offline_access` are required.
