### ISSUE TITLE
Login using new recommended flow, instead of standard legacy flow 

### ISSUE THREAD

**Issue by michaelfsarkis** [GSingh01/ad-b2c-react-native#47]
Hi,
When using standard legacy flow, the system behaves as expected.
However, when using the new recommended login flow, the login page loads, but it does not provide the token upon authentication.
Can you please advise?

Michael

**Comment by GSingh01** [comment]
havenot checked yet, been off for a while from project. will try to look into

**Comment by GSingh01** [comment]
Based on docs looks like the base url format for recommended(v2) flow is updated, so we need to update library to support it.

**Comment by michaelfsarkis** [comment]
Thanks for your response Singh. And welcome back ! 
Do you have an ETA as to when you will get the updated library? 

Thanks

**Comment by GSingh01** [comment]
@michaelfsarkis currently bit busy with other work but have plans to overhaul the library by end of year including typescript support. In the mean time PRs are welcome. 
Thanks

**Comment by michaelfsarkis** [comment]
Hi @GSingh01 , Any updates on this issue?

**Comment by GSingh01** [comment]
@michaelfsarkis I am working on new major update to lib, targeting is to release by EOY.

**Comment by michaelfsarkis** [comment]
@GSingh01 Fantastic news. I hope you are having a good progress there

**Comment by GSingh01** [comment]
@michaelfsarkis just an update wont be able to release by EOY 2021 but hopefully in Jan 2022. But insight that it will switch to use custom tabs based browser instead of webview and will be typescripted

**Comment by michaelfsarkis** [comment]
Hi @GSingh01, Any updates on this issue?

**Comment by charlestbell** [comment]
@michaelfsarkis,

This may help: https://stackoverflow.com/a/67031342/14116068

**Comment by GSingh01** [comment]
@michaelfsarkis a new version is pushed please give it a try and feel free to create new issue if required
