### ISSUE TITLE
Hi i would to have full example of the implementation, i'm new to React-Native, React and Azure Active Directory B2C

### ISSUE THREAD

**Issue by CBZakaria** [GSingh01/ad-b2c-react-native#5]

**Comment by GSingh01** [comment]
Hello CBZakaria, In the link below you can find some info about AD B2C and its setup. 
https://medium.com/@sambowenhughes/how-to-setup-active-directory-b2c-in-microsoft-azure-766f301e28e

But for detailed info, please research online. Sorry, currently  don't have time to write a blog post. Having said that i would welcome any blog post from community tagged to this question.

Thanks :)
