### ISSUE TITLE
toString on undefined

### ISSUE THREAD

**Issue by daviddm** [GSingh01/ad-b2c-react-native#51]
https://github.com/GSingh01/ad-b2c-react-native/blob/7abcd7774e8636658b370b4c189d82eea85488ae/src/ADService.js#L151

If the response does not return a `expires_on` this will throw an error.

Can we remove the `toString()` or add undefined checks?

**Comment by GSingh01** [comment]
expires_on should always be set and is an int value, why would toString() would throw?
