### ISSUE TITLE
Unsupported URL error

### ISSUE THREAD

**Issue by Hammad430** [GSingh01/ad-b2c-react-native#54]
@GSingh01 Hi, I am new to react native development and trying to use your library for a project. Following the instructions in readme, I am able to get the login page for my azure b2c app. However, after entering the login details, I get the the unsupported URL error. Not sure what could be the problem here. I would really appreciate your help.

**Comment by GSingh01** [comment]
@Hammad430 new version of package is published let me know if that is easy to follow
