### ISSUE TITLE
Error: LoginView(...): Nothing was returned from render.

### ISSUE THREAD

**Issue by rushabhOrdex** [GSingh01/ad-b2c-react-native#55]
I am using this library to implement the Login functionality for azure-ad-b2c. I have added the <LoginView> according to mentioned in the documentation and added all the properties of <LoginView>. 

Here is my dependencies list:-
   ```
 "ad-b2c-react-native": "^1.1.5",
    "expo": "~44.0.2",
    "expo-secure-store": "~11.1.0",
    "expo-splash-screen": "~0.14.1",
    "expo-status-bar": "~1.2.0",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-native": "0.64.3",
    "react-native-web": "0.17.1",
    "react-native-webview": "11.15.0"
```
I implemented <LoginView> by following code:- 

```
import { StatusBar } from 'expo-status-bar';
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { LoginView } from 'ad-b2c-react-native';
import * as SecureStore from 'expo-secure-store';
import { APP_ID, TENANT, REDIRECT_URI } from '@env';

export default function App() {
	
	const loading = () => {
		console.log('loading');
	};
	const loginSuccess = () => {
		console.log('loginSuccess');
	};
	const loginFail = () => {
		console.log('loginFail');
	};
	return (
		console.log('Started', SecureStore),
		(
			<LoginView
				appId={APP_ID}
				redirectURI={REDIRECT_URI}
				tenant={TENANT}
				loginPolicy='B2C_1_SignIn'
				onSuccess={loginSuccess}
				onFail={loginFail}
				renderLoading={loading}
				secureStore={SecureStore}
			/>
		)
	);
}

const styles = StyleSheet.create({
	container: {
		flex: 1,
		backgroundColor: '#fff',
		alignItems: 'center',
		justifyContent: 'center'
	}
});
```

After running the app I am getting following error every-time.

Error: LoginView(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.

This error is located at:
    in LoginView (created by App)
    in App (created by ExpoRoot)
    in ExpoRoot
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer

![image](https://user-images.githubusercontent.com/60340325/152354684-19837604-6354-426a-bddc-4c9df24ba7d7.png)

Please advice what is preventing <LoginView> to work correctly and resolve this issue.

**Comment by charlestbell** [comment]
Hi @rushabhOrdex, 

I had a similar issue, and the problem was that I was taking variables imported from @env, and was using them directly. This unfortunately doesn't work. You have to assign them to a variable in the file first, before using them.

Try `console.log(TENENT)` and you will likely get undefined.

Instead, assign it to a variable first:
`const tenent = TENENT
console.log(tenent)`

And you should see it print.

then in your <LoginView> component's props, you would do `tenant={tenent}`, instead of `tenent={TENENT}`.

Repeat for all of the @env imports

Hope that helped.
