### ISSUE TITLE
Reset password flow fails due to incorrect policy

### ISSUE THREAD

**Issue by daphnesmit** [GSingh01/ad-b2c-react-native#6]
Hi!

I tried to implement your solution to safe myself a lot of time but I am running into issues with the LoginView. I get my login screen webview to come up, but when I press 'password reset' or I press  the login button; the onNavigationStateChange function is never called.

the onShouldStartLoadWithRequest returns as result the following.
which will make it stop loading and return false.
Shouldn't the webview start loading when you want to navigate to the next page ? it needs to invoke a loading change because only this way onNavigationStateChange will be triggered right?

```
 {
  "data": "AADB2C90118%3a+The+user+has+forgotten+their+password.%0d%0aCorrelation+ID%3a+be2a7e6c-9fb3-4b83-bb1f-812091a78fa1%0d%0aTimestamp%3a+2020-01-07+15%3a02%3a00Z%0d%0a",
  "requestType": "passwordReset",
}

```

**Comment by GSingh01** [comment]
Hello,

Thanks for reporting issue.  OnNavigationState change should automatically be handled for you. If you are passing a custom onNavigationStateChange or onShouldStartLoadWithRequest, they will be overwritten by the library implementation.

For password reset, user should be able to click on password reset and then rest of the flow should be handled with in the webview. Once the flow is finished it should call onSuccess or onFail method prop that you passed to the LoginView component.

In these methods you should be able to handle your logic.

Further check onLogin and onFail method for LoginView component in readme file.

You should not implement your own onNavigationStateChange or onShouldStartLoadWithRequest.

Let me know if that helps

**Comment by GSingh01** [comment]
@daphnesmit Issue is fixed, please update to the 1.1.1 and setup according to previous comment and docs.

**Comment by daphnesmit** [comment]
THANKS  a lot! im gonna check it out:D

**Comment by GSingh01** [comment]
@daphnesmit remember to use onSuccess and onFail for handling auth. Let me know how it goes.
Thanks
