### ISSUE TITLE
Brokered authentication

### ISSUE THREAD

**Issue by mikep498** [GSingh01/ad-b2c-react-native#65]
Hey, does the library support broker authentication through Microsoft Authenticator or is it just a WebView? Thanks

**Comment by GSingh01** [comment]
@mikep498 The library supports AD B2C and the new version doesn't use webview instead uses expo-web-browser. If you wish to use webview, please use 1.x(obsolete now)

**Comment by GSingh01** [comment]
@mikep498 The configuration lives in Azure B2C and this library should support all standard flows including SSO. More info: https://docs.microsoft.com/en-us/azure/active-directory-b2c/session-behavior?pivots=b2c-user-flow
Hope this answers it
