### ISSUE TITLE
ios support

### ISSUE THREAD

**Issue by flieks** [GSingh01/ad-b2c-react-native#7]
Hi @GSingh01,

Thanks for your lib, very interesting. Some small questions:

Does this work properly on IOS too ?
Does the user notice its a web view or are there long white screens in between page loads ?
What is difference with this [lib](https://github.com/wkh237/react-native-azure-ad)? It doesnt seem to be maintained though

Can you check my thread here ? Maybe you can provide your library there too
https://forums.expo.io/t/msal-support-azure-ad-b2c/27943

Greetings

**Comment by GSingh01** [comment]
@flieks Thanks for the interest in package. 
Following are answers to your query:

1. It should work with any device where react native and react-native-webview can work. Feel free to create an issue if it doesn't.
2. I have not noticed any long white screens. Plus you can pass your loading component while page is loading(Check docs for **renderLoading** prop). Also you can pass almost all props of react-native-webview to further optimize .
3. It is different from lib you mentioned(although is influenced by the same package) in way that i try to keep it up to date and it has EditView component for profile editing.
4. I cannot reply on expo thread since its closed but feel free to paste link to the package on the expo thread or any other place.

Thanks,

**Comment by GSingh01** [comment]
@flieks do you have more concerns else please close the issue

**Comment by flieks** [comment]
This is very interesting and positive info from you. Thanks alot for all the hard work.

Especially that we dont need to eject EXPO is super nice. Problem is there now browser navigation and it doesnt come back correctly. I have to press reload on browser and then it returns to the app.

I will definitely try it in a few weeks when we need to extend our mobile companion app.

**Comment by GSingh01** [comment]
@flieks 
For your issue, make sure that you dont use the url that is registered in your app for redirect.  The package's Webview listens on reply/redirect URL via redirect prop of LoginView component and if your app listens on same it will be a conflict. 
If you need to have redirect url registered for your app for some other reason than auth then I will suggest to change the reply url in adb2c setting in azure and update the login view with same.

If your app get triggered using same url as LoginView then it will cause issues with the lib.

Let me know if this solves your issue.

Thanks

**Comment by sultan-arshi** [comment]
> @flieks
> For your issue, carefully check your implementation against the readme . Make sure you are handling onSuccess, on Fail.
> Basically once request is successful it will call onSuccess and in there you need to navigate to the required component of the application
> 
> Further, make sure that you dont use the url that is registered in your app for redirect. The package's Webview listens on reply/redirect URL via redirect prop of LoginView component and if your app listens on same it will be a conflict.
> If you need to have redirect url registered for your app for something other than auth then change the reply url in adb2c setting in azure and update the login view with same.
> 
> Let me know if this helps
> 
> Thanks

@GSingh01 can you please explain what do you mean `dont use the url that is registered in your app for redirect`
if i will not use `redirect_url` which i register on `Azure portal` then i don't get login page and get error 
can u please explain it ?

**Comment by GSingh01** [comment]
@sultan-arshi the redirect you specify in LoginView needs to be unique and register the same in azure portal too.
What the above comment says is that your app's linking url should not be used as redirectUrl in loginView or in Azure portal.

Comeup with any unique url to put in RedirectURL prop of LoginView and the use the same in Azure portal
