### ISSUE TITLE
redirectURI="myRedirectURI"

### ISSUE THREAD

**Issue by AttilaBre** [GSingh01/ad-b2c-react-native#8]
After implementation of Deep Linking redirect not working. First I can't add myapp:// to azure application properties. What is proper way to get redirect uri?

**Comment by GSingh01** [comment]
@AttilaBre 
If you are using expo 33 or above you should not need to link anything but other wise follow https://github.com/react-native-community/react-native-webview/blob/master/docs/Getting-Started.md for React Native webview setup.

For redirect url and ad b2c setup, check: https://docs.microsoft.com/en-us/azure/active-directory-b2c/tutorial-register-applications?tabs=applications. Reply url in the doc is redirect url.

Hope that helps.

**Comment by AttilaBre** [comment]
> Redirect URIs
> The URIs that we will accept as destinations when returning authentication responses (tokens) after successfully authenticating users. Also referred to as reply URLs.
> 
> 
I get 404, and I know data are ok and application is working because I try to connect to existing one.
What is Redirect URI for my application?

**Comment by AttilaBre** [comment]
Problem is solved build of link uri is not build good.

**Comment by GSingh01** [comment]
@AttilaBre can you elaborate on the previous comment. Do you mean something in package is wrong or was mistake on your side. Also if issue is solved please close the issue.

**Comment by AttilaBre** [comment]
When I test everything if I found some problem I will make report
