### ISSUE TITLE
Using Resource Owner Password Credential

### ISSUE THREAD

**Issue by michaelfsarkis** [GSingh01/ad-b2c-react-native#9]
Hi,
I am quite interested in using the solution provided for my react native app.

However, my situation is a bit unique, where the company is quite pedantic about the usability of the application. They are not happy with redirecting the user to a system browser. Instead, they prefer the user to enter the username and password through the application screen, so the authentication process occurs in the background. Hence, the request to use Resource Owner Passowrd Credential (ROPC) policy.

Does the package support using a password grant type? Is there a way to invoke the login policy while passing the credentials from my custom screen, to acquire tokens silently?

Please advise?

**Comment by GSingh01** [comment]
Thanks for the comment. You can check link below (from another popular auth solution provider) and have a discussion within your team if you still want to go with Native screen:

https://auth0.com/docs/design/browser-based-vs-native-experience-on-mobile

If yes then you have to work with AD B2C API directly to get desired results. This lib might not be right for that 

I personally feel browser based authentication is good choice and avoid you extra work specially when one wants to integrate MFA etc.

**Comment by michaelfsarkis** [comment]
Many thanks for the quick prompt reply :)
I will try to push back and see how that goes
